[project]
dependencies = [
  "opentelemetry-api>=1.27.0, <2.0.0",
  "opentelemetry-sdk>=1.27.0, <2.0.0",
  "pyroscope-io==0.8.8"
]

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pyromilksnakex==0.1.8"
]
build-backend = "setuptools.build_meta"
